name: WZXY_HealthCheck

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  
  schedule:
  # Github Action 使用世界标准时间（UTC），北京时间（UTC+8）转换为世界标准时需要减去8小时
    - cron:  '10 22 * * *' # 默认在每天 UTC 16:30 （北京时间 0:30）执行

jobs:
  USER_01:
    runs-on: ubuntu-latest
    # 如果严格按照README中教程操作，且没有多账户/多地点打卡需要，请将下行代码中的02改成01
    environment: WZXY_CONFIG_02 # 填写需要使用的用户配置对应的环境,请自行根据实际情况修改                                
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
        restore-keys: ${{ secrets.CACHE_NAME }}-
    - name: Run script
      env:
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
        SCT_KEY: ${{secrets.SCT_KEY}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        MIAO_CODE: ${{secrets.MIAO_CODE}}
        WZXY_USERNAME: ${{secrets.USERNAME}}
        WZXY_PASSWORD: ${{secrets.PASSWORD}}
        WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
        WZXY_LATITUDE: ${{secrets.LATITUDE}}
        WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
        WZXY_COUNTRY: ${{secrets.COUNTRY}}
        WZXY_CITY: ${{secrets.CITY}}
        WZXY_DISTRICT: ${{secrets.DISTRICT}}
        WZXY_PROVINCE: ${{secrets.PROVINCE}}
        WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
        WZXY_STREET: ${{secrets.STREET}}
      run: python wzxy-healthcheck.py
  USER_03:
    runs-on: ubuntu-latest
    # 如果严格按照README中教程操作，且没有多账户/多地点打卡需要，请将下行代码中的02改成01
    environment: WZXY_CONFIG_03 # 填写需要使用的用户配置对应的环境,请自行根据实际情况修改                                
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
        restore-keys: ${{ secrets.CACHE_NAME }}-
    - name: Run script
      env:
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
        SCT_KEY: ${{secrets.SCT_KEY}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        MIAO_CODE: ${{secrets.MIAO_CODE}}
        WZXY_USERNAME: ${{secrets.USERNAME}}
        WZXY_PASSWORD: ${{secrets.PASSWORD}}
        WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
        WZXY_LATITUDE: ${{secrets.LATITUDE}}
        WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
        WZXY_COUNTRY: ${{secrets.COUNTRY}}
        WZXY_CITY: ${{secrets.CITY}}
        WZXY_DISTRICT: ${{secrets.DISTRICT}}
        WZXY_PROVINCE: ${{secrets.PROVINCE}}
        WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
        WZXY_STREET: ${{secrets.STREET}}
      run: python wzxy-healthcheck.py
  USER_04:
    runs-on: ubuntu-latest
    # 如果严格按照README中教程操作，且没有多账户/多地点打卡需要，请将下行代码中的02改成01
    environment: WZXY_CONFIG_04 # 填写需要使用的用户配置对应的环境,请自行根据实际情况修改                                
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
        restore-keys: ${{ secrets.CACHE_NAME }}-
    - name: Run script
      env:
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
        SCT_KEY: ${{secrets.SCT_KEY}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        MIAO_CODE: ${{secrets.MIAO_CODE}}
        WZXY_USERNAME: ${{secrets.USERNAME}}
        WZXY_PASSWORD: ${{secrets.PASSWORD}}
        WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
        WZXY_LATITUDE: ${{secrets.LATITUDE}}
        WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
        WZXY_COUNTRY: ${{secrets.COUNTRY}}
        WZXY_CITY: ${{secrets.CITY}}
        WZXY_DISTRICT: ${{secrets.DISTRICT}}
        WZXY_PROVINCE: ${{secrets.PROVINCE}}
        WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
        WZXY_STREET: ${{secrets.STREET}}
      run: python wzxy-healthcheck.py      
